### ISSUE TITLE
Invalid State on Ubuntu 14.04 Server

### ISSUE THREAD

**Issue by rothnic** [CenturyLinkLabs/panamax-ui#511] opened 2015-03-09 16:41 UTC
Ubuntu Version:
`Linux ubuntu-14 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Lots of layers, but this is on a windows machine with an Ubuntu VM. I tried the Windows install but there was some strangeness when it came to the formatting of things in some of the pages, so I was trying the ubuntu install method, but my issue may be I'm using ubuntu server.

The error I see is this:
```
Enter memory (MB) to be allocated to Panamax VM(1536):
Enter CPUs to be allocated to Panamax VM(2):
Enter version you want to use(dev/stable, defaults to:stable)
Would you like Panamax to create the alias (panamax.local)? (You will be prompted for sudo creds) [y/N]:y

Setting local alias to panamax.local
/home/vagrant/.panamax/desktop: line 103: bc: command not found
**Same thing about 100 times**

Reinstalling Panamax...
Would you like to re-download coreos base box[y/N]: n
UUID changed to: 1d39386f-7c2a-4994-b1b4-c11b117a785d
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%

Creating a new CoreOS VM...
UUID changed to: a6939527-4751-41d0-bded-b5764cd0ebc2
Bringing machine 'panamax-vm' up with 'virtualbox' provider...
==> panamax-vm: Importing base box 'panamax-coreos-box-522.6.0'...
==> panamax-vm: Matching MAC address for NAT networking...
==> panamax-vm: Setting the name of the VM: panamax-vm
==> panamax-vm: Clearing any previously set network interfaces...
==> panamax-vm: Preparing network interfaces based on configuration...
    panamax-vm: Adapter 1: nat
    panamax-vm: Adapter 2: hostonly
==> panamax-vm: Forwarding ports...
    panamax-vm: 22 => 2222 (adapter 1)
==> panamax-vm: Running 'pre-boot' VM customizations...
==> panamax-vm: Booting VM...
==> panamax-vm: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
VM Creation failed. Exiting.
```

I installed bc in ubuntu. Then re-installed, and ended up with the same issue at the end. I tried starting the VMs manually and got this:

```
vagrant@ubuntu-14:~$ VBoxManage list vms
"coreos_production_vagrant-522-6-0_1425918030074_20201" {bed27967-6cc5-4387-a5e8-342b9dacc195}
"panamax-vm" {60e08b91-d8c8-4875-b74c-7a4dba9a1282}
vagrant@ubuntu-14:~$ VBoxManage startvm panamax-vm
Waiting for VM "panamax-vm" to power on...
VBoxManage: error: The virtual machine 'panamax-vm' has terminated unexpectedly during startup with exit code 1

VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Machine, interface IMachine
vagrant@ubuntu-14:~$ VBoxManage startvm coreos_production_vagrant-522-6-0_1425918030074_20201
Waiting for VM "coreos_production_vagrant-522-6-0_1425918030074_20201" to power on...
VBoxManage: error: The virtual machine 'coreos_production_vagrant-522-6-0_1425918030074_20201' has terminated unexpectedly during startup with exit code 1
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Machine, interface IMachine
```

**Comment by cakkineni** [comment] 2015-03-09 18:59
@rothnic 
Thats quite a try :) ... yeah..thats way too many indirections happening in there...  Windows -> ubuntu -> coreos -> docker... . We tried a setup like this initially, the only one thing we noticed was, 
-  We had to enable `hardware assisted virtualization` flag on the base VM (inside virtualbox). 
-  We had to use ubuntu desktop. 

So when you mention `strangeness in formatting` of pages, what were you seeing? 

Also, another route you can possibly take is create a coreos vm and then install panamax into it, you'll need to follow cloud provider instructions for that.

**Comment by ckmaresca** [comment] 2015-06-04 17:46
I have the same issue on a virgin Ubuntu 14.x server using Vbox 4.3.28 and vagrant 1.7.2 - spent about an hour chasing it down, then gave up.  It seems to be a problem with vagrant communicating to virtualbox about hostonly network adapter setup.  

Here's a copy of my error if it helps:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: VBoxNetAdpCtl: ioctl failed for /dev/vboxnetctl: Inappropriate ioctl for devic
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 66 of file VBoxManageHostonly.cpp
```
Happens when you call `panamax init` or `panamax reinstall` or `vagrant up [id]` or try to start the vbox image.  

This is on a new install of Ubuntu Server 14.04.2 LTS (up to date as of this post) on a bare metal machine (not a cloud VM).  Note that using 'Ubuntu Desktop' is not a solution as this machine has no video card at all (well, I suppose I could export an X session, but this is supposed to be server software....).  Also, not sure how to set `hardware assisted virtualization` in virtualbox from the command line.

**Comment by Dulanjalie** [comment] 2015-06-24 22:02
i have the same issue with ubuntu 14.04 server. i installed ubuntu desktop packages but didnt help. 
bosh-lite@bosh-lite:~/workspace/bosh-lite$ vagrant --version
Vagrant 1.7.2
bosh-lite@bosh-lite:~/workspace/bosh-lite$ VBoxManage --version
4.3.28r100309

I doubt it a vagrant or Vbox issue since i was able to bring up hashicorp/precise32 successfully.

**Comment by Dulanjalie** [comment] 2015-06-25 20:27
seems like need to have VT-x enabled. I tried in a server where vt-x is enabled. it worked.

**Comment by cakkineni** [comment] 2015-08-26 21:52
Closing as the issue is resolved.

**Closed by cakkineni** 2015-08-26 21:52 UTC
